export const GET_ALL_APPOINTMENTS_BY_NAME_REQUEST =
  "GET_ALL_APPOINTMENTS_BY_NAME_REQUEST";
export const GET_ALL_APPOINTMENTS_BY_NAME_SUCCESS =
  "GET_ALL_APPOINTMENTS_BY_NAME_SUCCESS";
export const GET_ALL_APPOINTMENTS_BY_NAME_FAIL =
  "GET_ALL_APPOINTMENTS_BY_NAME_FAIL";

//Error constants
export const ERROR_MESSAGES_RESET = "ERROR_MESSAGES_RESET";
export const ERROR_MESSAGES_SUCCESS = "ERROR_MESSAGES_SUCCESS";
